POST http://localhost:3000/auth/registration
Content-Type: application/json

{
	"username": "admin",
	"password": "admin"
}

###

POST http://localhost:3000/auth/login 
Content-Type: application/json

{
	"username": "admin",
	"password": "admin"
}

###


GET http://localhost:3000/auth/Posts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODAxZTkzOTU1ZmZmMjMzMDQzMmY2OCIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTYxOTAyMDg0MiwiZXhwIjoxNjE5MDIxNzQyfQ.rZpMW48cBbFR5wfvphEjnyvjo_asCKNhHpKojnPesRk

###

POST http://localhost:3000/auth/createPost
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODAxZTkzOTU1ZmZmMjMzMDQzMmY2OCIsInJvbGVzIjpbIkFETUlOIl0sImlhdCI6MTYxOTAyNTA5NywiZXhwIjoxNjE5MDI1OTk3fQ.GEpOfXul9XFp9xeh5AdXDg-CzMUq4D4OkC5GjPXlLLg
Content-Type: application/json

{
	"Name": "dfsdf",
	"Description": "fsdfsdfsfadaa"
}