POST http://localhost:3000/auth/registration
Content-Type: application/json

{
	"username": "admin",
	"password": "admin"
}

###

POST http://localhost:3000/auth/login 
Content-Type: application/json

{
	"username": "user",
	"password": "user"
}

###


GET http://localhost:3000/auth//allPosts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODAxYjhkNzVjOTBjMjVkMDNmMDE3MyIsInJvbGVzIjpbInVzZXIiXSwiaWF0IjoxNjE5MTYyMTU3LCJleHAiOjE2MTkxNjM5NTd9.3Fm9x3IezIa-X38N83syVXjAuKoHOR2FULQ7DJurtMg

###

POST http://localhost:3000/auth/createPost
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODAxYjhkNzVjOTBjMjVkMDNmMDE3MyIsInJvbGVzIjpbInVzZXIiXSwiaWF0IjoxNjE5MTAyOTYzLCJleHAiOjE2MTkxMDQ3NjN9.tz41prl0HWy0WE9SRvAEtJ0fD64nI2qlAqB9BbWEu8k
Content-Type: application/json

{
	"name": "Posssdsdfsdffsddt",
	"description": "Newsdfsdf pdsfsdost testing "
}

###

GET http://localhost:3000/auth/myPosts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODAxYjhkNzVjOTBjMjVkMDNmMDE3MyIsInJvbGVzIjpbInVzZXIiXSwiaWF0IjoxNjE5MTAyOTYzLCJleHAiOjE2MTkxMDQ3NjN9.tz41prl0HWy0WE9SRvAEtJ0fD64nI2qlAqB9BbWEu8k

###

DELETE http://localhost:3000/auth/deletePost
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODAxYjhkNzVjOTBjMjVkMDNmMDE3MyIsInJvbGVzIjpbInVzZXIiXSwiaWF0IjoxNjE5MTAyOTYzLCJleHAiOjE2MTkxMDQ3NjN9.tz41prl0HWy0WE9SRvAEtJ0fD64nI2qlAqB9BbWEu8k
Content-Type: application/json

{
	"name": "Posssdsdfsdffsddt"
}

###

PUT http://localhost:3000/auth//editPost
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODAxYjhkNzVjOTBjMjVkMDNmMDE3MyIsInJvbGVzIjpbInVzZXIiXSwiaWF0IjoxNjE5MTAyOTYzLCJleHAiOjE2MTkxMDQ3NjN9.tz41prl0HWy0WE9SRvAEtJ0fD64nI2qlAqB9BbWEu8k
Content-Type: application/json

{
	"name": "Post",
	"newDescription": "This is my post mazafaka"
}